name: release-validation

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  network-performance:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Run Schmoder CI
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 # v1.3.2
        with:
          workflow: ci.yaml
          repo: coder/schmoder
          inputs: '{ "num_releases": "3", "commit": "${{ github.sha }}" }'
          token: ${{ secrets.CDRCI_SCHMODER_ACTIONS_TOKEN }}
          ref: main
